### ISSUE TITLE
Spotify Premium Issues and Suggestions

### ISSUE THREAD

**Issue by tnpl-home** [apkmody/apkmody.io#37]
Issues:
.The app has no described features upon the first few opening, basically function like a free google play spotify version. It does work as usual after a few time of turning it off then on again, however.
.Sometimes the now playing bar that is usually at the bottom at the screen won't appear.
.I couldn't find a few features mentioned in the description like: spotify connect, spotify inbox and storylines. Not sure if this is a bug or computer-only features.

Suggestions:
.I hope the team can add a feature that allow users to download songs and playlists on the team's spotify version if possible.

Overall, it has been a pleasant experience using your website and service. The site is designed and presented professionally, the amount of ads on the site is reasonable and doesn't affect the experience too much. I hope the team can improve more on the future. 

Thank you!

**Comment by anhphammody** [comment]
You can download the latest version of Spotify Premium here: https://apkmody.com/apps/spotify
