### ISSUE TITLE
Inappropriate pop ups

### ISSUE THREAD

**Issue by Disneymomma** [apkmody/apkmody.io#38]
I've been having pop-ups when I get on apkmody site but today it has inappropriate pop-ups, screen shot attached. I try to close them but they come right back.I'm afraid I'm going to have to stop using this site
![Screenshot_20220519-160831_Chrome](https://user-images.githubusercontent.com/98134887/169419041-89de5fff-701f-4aba-a6e3-a13d0d0aa605.jpg)

**Comment by anhphammody** [comment]
This site is not my site. My site is apkmody.com
